name: Run tests
on: [push]

jobs:
  test_words_replacer_app:
    runs-on: ubuntu-latest
    name: Run Tests 
    
    steps:
      - uses: actions/checkout@v3
     
      - name: Run test for words_replacer task
        run: |
          cd LR4
          cd replace_words
          make test
          make clean
          
  test_text_erros_fixer_task:
    runs-on: ubuntu-latest
    name: Run Tests 
    
    steps:
      - uses: actions/checkout@v3
     
      - name: Run test for text errors fixer task
        run: |
          cd LR4
          cd check_text_for_errors
          make test
          make clean
