name: Run tests
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Run Tests 
    
    steps:
      - uses: actions/checkout@v3
     
      - name: Build and push
        run: |
          cd LR4
          cd replace_words
          make test
          make clean
