name: LR4 - tests
on: [push]

jobs:
  test_words_replacer_app:
    runs-on: ubuntu-latest
    name: words replacer app
    
    steps:
      - uses: actions/checkout@v3
     
      - name: Run test for words_replacer task
        run: |
          cd LR4
          cd replace_words
          make test
          make clean
